apiVersion: v2
name: ska-mid-wms
description: A Helm chart for a WMS Tango device server.
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: ska-tango-base
    version: 0.4.15
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-util
    version: 0.4.15
    repository: https://artefact.skao.int/repository/helm-internal