# Default values for ska-mid-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
# image:
# repository: wms_tango_helm_dev
# This sets the pull policy for images.
# pullPolicy: IfNotPresent
# Overrides the image tag whose default is the chart appVersion.
# tag: "wms-tango"
deviceServers:
  wms:
    image: 
      image: ska-mid-wms-device
    instances: ["wms01"]
    server:
      name: "wms01"
      instances:
      - wms01:
        name: "wms01"
        classes:
          - WMSDevice:
            name: WMSDevice
            devices:
              - dev01:
                name: mid/wms/01

ska-tango-base:
  enabled: true
  itango:
    enabled: true
global:
  annotations:
    app.gitlab.com/app: taranta
    app.gitlab.com/env: taranta
  minikube: true
  tango_host: tango-databaseds:10000
  cluster_domain: cluster.local    
dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.12
    pullPolicy: IfNotPresent
    